export enum GameState {
  IDLE = 'IDLE',
  COUNTDOWN = 'COUNTDOWN',
  SHOW_SEQUENCE = 'SHOW_SEQUENCE',
  WAITING_FOR_INPUT = 'WAITING_FOR_INPUT',
  ROUND_RESULT = 'ROUND_RESULT',
  MATCH_RESULT = 'MATCH_RESULT',
}
